### PR TITLE
General updated plugin for Openfire 3.10

### PR DESCRIPTION
**Pull request by annovanvliet**
upgraded to maven-plugin-api 2.2.1

renamed to openfire-maven-plugin, because of of warning in build process;
using new version of dependencies,
resolved warnings in property resolving;

### CODE REVIEW

**Comment by srt** [comment]
Ok thanks, looks better now with the correct line encodings.
Do we really have to change the name? If we do the name of the repo and the artifact name no longer match, so I would like to only do this if there is no other option...

**Comment by annovanvliet** [comment]
I changed the name while during the build i got the following Error:

[INFO] --- maven-plugin-plugin:2.9:descriptor (default-descriptor) @
maven-openfire-plugin ---
[ERROR]

Artifact Ids of the format maven-___-plugin are reserved for plugins in the
Group Id org.apache.maven.plugins
Please change your artifactId to the format ___-maven-plugin
In the future this error will break the build.

So how prepared do you want to be for the furture? For the moment it does
not break the build, so you could do without the name change, but I don't
think there will be a lot of confusion when the artifact id does not match
the repo name.



2015-03-28 9:45 GMT+01:00 Stefan Reuter <notifications@github.com>:

**Comment by annovanvliet** [comment]
Ihave still a question.

When you use the ant/openfire build, the classes and the jsp are packaged in separate jars in the lib directory.
I noticed that the plugin builds a plugin jar with a classes directory with all classes separatly.

Is there an option to pack the class files in a separate jar?

**Comment by annovanvliet** [comment]
I changed the name while during the build i got the following Error:

*[INFO] --- maven-plugin-plugin:2.9:descriptor (default-descriptor) @ maven-openfire-plugin ---
[ERROR]*

* Artifact Ids of the format maven-___-plugin are reserved for plugins in the Group Id org.apache.maven.plugins. Please change your artifactId to the format ___-maven-plugin. In the future this error will break the build.*

So how prepared do you want to be for the furture? For the moment it does not break the build, so you could do without the name change, but I don't think there will be a lot of confusion when the artifact id does not match the repo name.

**Comment by who** [comment]
+1 

Please merge this PR, thanks.

**Comment by annovanvliet** [comment]
I added a bare openfire jar for dependency sake.

**Pull request merged**
